### ISSUE TITLE
DbApp Refactor Epic

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#112]
Epic to track individual refactoring issues
- [x] #114
- [x] #113
- [x] buda-base/archive-ops#827
- [x] buda-base/ao-google-books#54
When all that is done, you can then:
- [x] buda-base/archive-ops#810
- [x] buda-base/archive-ops#836

#836 was discovered after the release.

**Comment by jimk-bdrc** [comment]
All subissues are complete

**Comment by jimk-bdrc** [comment]
Not quite.
See [e05d6f9f](https://github.com/buda-base/archive-ops/commit/e05d6f9f82700cfdf22ce3c907596838779f6eb4) which needs to have the bdrc-util scripts redeployed.

**Comment by jimk-bdrc** [comment]
All issues closed
