### ISSUE TITLE
DRS Deposit Phase 2

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#121]
From HUL+BDRC meeting:

- [ ] HUL:CB:  50 records into production ALMA, return HOLLIS IDs
- [ ] BDRC:JK: 
            - [ ] update batchbuilder libraries
            - [ ] 1 deposit into production HUL:PA
            - [ ] When succeeds, 
 - [ ] BDRC:JK entire backlog MARC to HUL:CB
 - [ ] HUL:CB returns HOLLIS Ids
 - [ ] BDRC:JK Enter into DRS db
 - [ ] BDRC:JK Begin backlog processing
 - [ ] HUL:CB Create an entry for BDRC in auto ALMA - allows us to request and receive HOLLIS records in real time
 - [ ] BDRC:JK Create auto HOLLIS workflow

@jimk-bdrc will add issues as they become relevant. No need to clog the board now.

**Comment by jimk-bdrc** [comment]
DRS2 only. Different flow for DRS3.
